### ISSUE TITLE
Image widths do not get applied

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/srcset_image#1]
Sadly I've had a hard time getting this module to work correctly as the image widths for each srcset url do not get set, there's just a "w" after the url. 
 
I get this error message for each image style in the image set:

`Warning: getimagesize(https://link-to-image-style-image): failed to open stream: HTTP request failed! HTTP/1.1 503 Service unavailable in theme_srcset_image_formatter() (line 25 of /public_html/modules/srcset_image/srcset_image.theme.inc).`

And I accordingly see errors for each image style in the console:

`Failed parsing 'srcset' attribute value since its 'w' descriptor is invalid.`
`Dropped srcset candidate "<URL>"`

The 'solution' is to load each image style url in my browser, clear the site cache and then the module correctly adds the image widths. Obviously not ideal!

What's going on? Is it my server config, folder permissions or something else?

**Comment by greg-42droids** [comment]
I hope this helps to fix this:

```php
// Get the image size.
$style_url = image_style_url($image_style, $item['uri']);
$image_size = getimagesize($style_uri);
if (!empty($image_size)) {
  $srcset[] = $style_url . ' ' . $image_size[0] . 'w';
}
```
srcset_image/srcset_image.theme.inc @ line 43 getimagesize($style_url) should use $style_uri

**Comment by ghost** [comment]
You're right @greg-42droids! Thanks for that. I've committed https://github.com/backdrop-contrib/srcset_image/commit/cfbf13c9af3363909dd06225eb84898e9b01f947 which fixes this. @sbgraphicdesign can you please try the latest dev code to see if that fixes things for you?
