### ISSUE TITLE
Original image is still included as src even if "Include original image" is deselected

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/srcset_image#2]
I was somewhat surprised to discover that the uploaded image is used for the default image in the srcset. I was expecting to only see those image styles that have been added to the image set.

On the basis that many users upload images with scant regard to image proportions or file size – for example straight from a stock image library – the default image could very well be totally inappropriate for use in its raw form on the site.

Therefore can I make a suggestion that one of the image styles in the image set must be set as the default image please?

**Comment by lucyconnuk** [comment]
Hi sbgraphicdesign
Also currently playing with this module. I just wondered if the issue that you mention above can be solved by unchecking the "Include original image" box as shown below?
![image](https://user-images.githubusercontent.com/88381184/142181879-281f7137-700c-4d2d-8f1b-a56c72ece801.png)

**Comment by sbgraphicdesign** [comment]
Hi Lucy, sorry I don't see that option anywhere, not in Views or the content type display options.

**Comment by ghost** [comment]
@sbgraphicdesign Is this still an issue for you? It does sound like you just need to disable that checkbox, which is definitely there: https://github.com/backdrop-contrib/srcset_image/blob/694e19ef42d5aceaa74cf1aa992e94a0f6304f51/srcset_image.module#L123-L128

**Comment by yorkshire-pudding** [comment]
I confirm this is a bug.  Yes, the option deselected means the original size isn't included in the srcset. However, the original image is still included as `src` within the image attributes.

Let's say our image style includes a watermark to protect the intellectual property of the original image; in this case it would be possible for someone to get the original image.

Fix in progress.

**Comment by yorkshire-pudding** [comment]
Hi @sbgraphicdesign - I'm not sure if you're still around (your website says you still do Backdrop).  I've created a pull request that changes it so that if original is not included, then the largest style file will be included as the `src`.

If you want to test, then great. If not, I will merge and release.
