### ISSUE TITLE
Lazy Loading?

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/srcset_image#3]
Would it be possible to have srcset images lazy loaded, seeing as this is now in core?

**Comment by yorkshire-pudding** [comment]
Hi @sbgraphicdesign - I've added a PR for this if you want to test. If not, I'll release.

**Comment by laryn** [comment]
@yorkshire-pudding I was looking at your PR because I might need to do something similar in `picture` (I haven't looked at the lazy loading there yet, although the scaffolding is in place), and I saw the note about 'auto'. I dug a big and [found a source](https://web.dev/articles/browser-level-image-lazy-loading) that claims:

> Previously, Chromium automatically lazy-loaded any images that were well suited to being deferred if [Lite mode](https://blog.chromium.org/2019/04/data-saver-is-now-lite-mode.html) was enabled on Chrome for Android and the `loading` attribute was either not provided or set as `loading="auto"`. However, [Lite mode has been deprecated](https://support.google.com/chrome/thread/151853370/sunsetting-chrome-lite-mode-in-m100-and-older) (as was the non-standard `loading="auto"`) and there are currently no plans to provide automatically lazy-load of images in Chrome.

**Comment by yorkshire-pudding** [comment]
@laryn 

Thanks for this; I was copying what core did.  What do you think would be best as the unset option? 'Default' rather than 'Automatic'?

**Comment by laryn** [comment]
@yorkshire-pudding Probably so, but maybe open an issue for core since we'll need to address this there, too, and could get a wider range of input on that question.

**Comment by laryn** [comment]
I guess you could implement this one as you wish since you haven't had this feature implemented yet. I'd recommend "Default" as the unspecified option.

**Comment by yorkshire-pudding** [comment]
Thanks @laryn . I've gone with default for now. Happy to reconsider if/when core is updated.
