### ISSUE TITLE
Module doesn't work with latest release of Preset

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/srcset_image#6]
Preset  v2.0.0.+ changed the way config is stored and causes this module to stop working.

I've figured out the fix on a site I'm building and will get a PR in shortly

**Comment by laryn** [comment]
@yorkshire-pudding Sorry about this! I think it was my fault, not fully thinking through the ramifications of Preset 2.0's changes, otherwise I'd have given a broader warning and some lead time.

**Comment by yorkshire-pudding** [comment]
@laryn - no problem. It was an interesting learning experience, and now this module has a maintainer, which it might not have got if it worked perfectly for me.
